# rustfmt options
# docs at https://rust-lang.github.io/rustfmt/
array_width = 60
#comment_width = 80 # unstable (Nightly only)
edition = "2021"
fn_call_width = 120
force_explicit_abi = true
#group_imports = "StdExternalCrate" # unstable (Nightly only)
hard_tabs = false
#imports_granularity = "Module" # unstable (Nightly only)
#imports_layout = "Vertical" # unstable (Nightly only)
match_arm_leading_pipes = "Preserve"
max_width = 110
merge_derives = true
newline_style = "Unix"
#normalize_doc_attributes = true # unstable (Nightly only)
remove_nested_parens = true
#reorder_impl_items = true # unstable (Nightly only)
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 60
single_line_if_else_max_width = 100
#struct_lit_single_line = false # unstable (Nightly only)
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = false
#version = "Two" # unstable (Nightly only)
#wrap_comments = true # unstable (Nightly only)
